### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/skia#1]
Hello @achicu, I'm Fil from Adobe's Open Source Office. Just checking in, is this project still active? Is there value in having this continue to be around?

If yes, I'd like to send some pull requests to update documentation, contribution guidelines, that kind of stuff.

If no, I suggest we archive the project.

Let me know your thoughts.

**Comment by dirkschulze** [comment]
@filmaj No it is not and can get archived.

**Comment by filmaj** [comment]
OK I've updated the README and will archive shortly.
